### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-ghost-frogs#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
• The navbar will be located in the navbar.js file - - bootstrap will be used to create the navbar
• The navbar will be sticky
• The logo will be on the far left of the navbar
• The input section will span 75% of the navbar
• The clear button will be located on the far right of navbar

**Comment by rtate2** [comment]
<img width="329" alt="Screen Shot 2019-10-15 at 9 30 00 PM" src="https://user-images.githubusercontent.com/54008854/66883346-3c280f00-ef93-11e9-85bd-fb50709e9645.png">
