### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-ghost-frogs#14]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
• The clear message function will be located in the clear-messages.js file and will be exported and imported to the main.js and be called in the init function.
• jQuery will be imported to the file
• Create an event listener attached to the "clear" button within the navbar
• Use the jQuery empty() method to create a find function that calls all existing messages within message container and deletes them.
• Export function and import into main.js; run it with the init function.

**Comment by rtate2** [comment]
<img width="329" alt="Screen Shot 2019-10-16 at 6 12 11 PM" src="https://user-images.githubusercontent.com/54008854/66965790-9206c080-f040-11e9-9d5d-f18d5b01ee62.png">
