### ISSUE TITLE
Large Text

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-ghost-frogs#15]
## User Story
As a user, with tired eyes, I should be able to chat with large text.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Large Text"
**And** they should be able to click this checkbox
**And** when the checkbox is selected all the message text should be larger

## Dev Notes
- Create a checkbox in the fixed footer bar at the bottom of the application that has a label of "Large Text"
- Create a listener on the checkbox that if its value is "checked" the text on the page will increase in size
- Create a function that will use jquery to target the message containing components on the page.
- Use this [link](https://www.pair.com/support/kb/resize-sites-font-jquery/) to help create a function that will make the text larger in each of the components that are targeted

**Comment by broach44** [comment]
https://www.pair.com/support/kb/resize-sites-font-jquery/
