### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-ghost-frogs#2]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
- Create a fixed footer at the bottom of the page
- Create a checkbox with a label for "Dark Theme"
- Add a listener to the checkbox
- When the checkbox is checked it should trigger an event to change the theme using Sass and the theme map created.  A jQuery selector and toggleClass can assign the class by targeting the wrapper for all the content on the page.
- When the checkbox is unchecked it should trigger an event and change back to the light theme

**Comment by broach44** [comment]
## Darker color scheme
black: `000000`
dark gray: `212121`
off white: `b3b3b3`
lighter gray blue: `547c94`
darker gray blue: `045a7b`
